server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloud
    password: cloud1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
