server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         # 开启动态路由 -根据服务名负载均衡实现动态路由
      routes:
        - id: payment_route                     # 路由id，没有固定规则，要求唯一，建议配合服务名
          #uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment       # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**              # 断言，路径相匹配的进行路由

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment       # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery

        - id: payment_route3
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka